### ISSUE TITLE
No database when using the application demo

### ISSUE THREAD

**Issue by fengh16** [Kaimary/GAR#2]
In http://47.116.100.156:30279/#/chat , when I click "Choose", there is no database in the list.

![image](https://github.com/Kaimary/GAR/assets/22994178/076bbca5-abf4-45a2-bf04-a06ac4d7e727)

There is also an error 未查找到可用表

![image](https://github.com/Kaimary/GAR/assets/22994178/2f1c059b-76c3-4c92-93be-316dec16ae8f)

**Comment by Kaimary** [comment]
@fengh16 Hi! Thanks for the report. The demo service is available now. Please try and let me know if you still have the issue.

**Comment by fengh16** [comment]
Thank you for your reply. The demo now works!
