### ISSUE TITLE
 Can i directly run the evaluation script in my system without training

### ISSUE THREAD

**Issue by hmhm1190** [Kaimary/GAR#4]
Would you explain each term in code to run the training script as well as evaluation script: 
$ bash train_pipeline.sh <dataset_name> <train_data_path> <dev_data_path> <table_path> <db_dir>

Would you pls verify: 
Dataset name: spider
train_data_path: /c/Users/Lenovo/GAR/datasets/train_spider.json
dev_data_path: /c/Users/Lenovo/GAR/datasets/dev.json
table_path: /c/Users/Lenovo/GAR/datasets/spider/tables.json
db_dir: /c/Users/Lenovo/GAR/datasets/spider/database

**Comment by Kaimary** [comment]
@hmhm1190 The above parameter settings look good! What error do you have now?

**Comment by hmhm1190** [comment]
While installing the dependencies I am getting this error. Can I try and install latest versions of all libraries by simply removing the version number in the requirements.txt ?

**ERROR: Could not find a version that satisfies the requirement torchvision==0.8.2 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1)
ERROR: No matching distribution found for torchvision==0.8.2
(test)**

**Comment by Kaimary** [comment]
@hmhm1190 I am afraid not; there may have some conflicts if you remove the version number.
I did not test before, so my suggestion is to follow to use the libraries we provided in the requirements file. Thanks!

**Comment by hmhm1190** [comment]
@Kaimary Thanks for Responding...

But now I am getting another error:

**`OSError: /home/husain/GAR/saved_models/gar.spider/retrieval_model/stsb-mpnet-base-v2 does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/husain/GAR/saved_models/gar.spider/retrieval_model/stsb-mpnet-base-v2/None' for available files.
RESULT REPORT: Re-ranker test data generation failed!`** 

I am attaching the output log file here...
[output_test_GAR.txt](https://github.com/Kaimary/GAR/files/11687132/output_test_GAR.txt)

**Comment by Kaimary** [comment]
@hmhm1190 I checked the output file, and it looks like the first-stage ranking model (retrieval model) does not exist,
No sentence-transformers model found with name /home/husain/GAR/saved_models/gar.spider/retrieval_model/stsb-mpnet-base-v2

Please make sure you have trained the first-stage ranking model before generating the data for the second-stage ranking model, as the generation process relies on the first-stage ranking model.

**Comment by hmhm1190** [comment]
Thank You very much @Kaimary
