### ISSUE TITLE
Error in Reading Dataset for training

### ISSUE THREAD

**Issue by hmhm1190** [Kaimary/GAR#6]
I am trying to train the model but I am getting 
`"AssertionError: Error col: "value""` , 

I have attached the entire output log.
 
[New Text Document.txt](https://github.com/Kaimary/GAR/files/11687084/New.Text.Document.txt)

**Comment by Kaimary** [comment]
@hmhm1190 As mentioned in another [issue](https://github.com/Kaimary/GAR/issues/3#issue-1711414610), it was due to a normalization bug in the Spider data. Please use the updated data to have a try.

**Comment by hmhm1190** [comment]
Thank you very much @Kaimary
