### ISSUE TITLE
Problems when self.skeletons is an empty list

### ISSUE THREAD

**Issue by fengh16** [Kaimary/GAR#7]
I suggest to add an assert statement `assert self.skeletons, "self.skeletons is []"` before    https://github.com/Kaimary/GAR/blob/bc3de0a56d3e3c0d3cf4719d5011a1aec1bde52f/generator/QunitGenerator/qunit_generator.py#L78 .

This is because when `self.skeletons` is `[]`, we will make `self.combinatorial_rule_base["skeleton"]` to be `[]` and will return None in the function in `_default_choice` in https://github.com/Kaimary/GAR/blob/bc3de0a56d3e3c0d3cf4719d5011a1aec1bde52f/generator/QunitGenerator/qunit_generator.py#L259 and `choice(self, node_name, state_machine)` in https://github.com/Kaimary/GAR/blob/bc3de0a56d3e3c0d3cf4719d5011a1aec1bde52f/generator/QunitGenerator/qunit_generator.py#L242 which is used in https://github.com/Kaimary/GAR/blob/bc3de0a56d3e3c0d3cf4719d5011a1aec1bde52f/generator/QunitGenerator/qunit_generator.py#L439.

If the returned value of `dfs_random` is `None`, https://github.com/Kaimary/GAR/blob/bc3de0a56d3e3c0d3cf4719d5011a1aec1bde52f/generator/QunitGenerator/qunit_generator.py#L540 will always cause `ret = None` and make `while True:` a dead cycle.

------------------

This problem occurs for me because the file `serialization/gar.spider/qunits.json` contains `{'global_syntactic': {'max_projection_num': 0, 'max_where_predicate_num': 0, 'max_having_predicate_num': 0, 'has_output': False, 'has_iue': False, 'has_group': False, 'max_group_num': 0, 'max_where_nested_num': 0, 'max_having_nested_num': 0, 'max_iue_num': 0, 'max_order_num': 0, 'has_where': False}, 'units': [], 'skeleton': []}` for `concert_singer`. After deleted this file, the code works.

**Comment by Kaimary** [comment]
@fengh16 Thanks for your kind suggestion! Already committed the change as you suggested!
